/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge37;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.HashMap;

class AppTest {
        @Test
        public void testBusinessTripWithValidTrip() {
            HashMap<String, HashMap<String, Integer>> flights = new HashMap<>();
            flights.put("CityA", new HashMap<String, Integer>(){{put("CityB", 50);}});
            flights.put("CityB", new HashMap<String, Integer>(){{put("CityC", 30);}});
            flights.put("CityC", new HashMap<String, Integer>(){{put("CityD", 20);}});

            String[] validTrip = {"CityA", "CityB", "CityC", "CityD"};
            Integer result = Graph.businessTrip(flights, validTrip);

            assertNotNull(result);
            assertEquals(Integer.valueOf(100), result);
        }

        @Test
        public void testBusinessTripWithInvalidTrip() {
            HashMap<String, HashMap<String, Integer>> flights = new HashMap<>();
            flights.put("CityX", new HashMap<String, Integer>(){{put("CityY", 40);}});
            flights.put("CityY", new HashMap<String, Integer>(){{put("CityZ", 25);}});

            String[] invalidTrip = {"CityX", "CityZ"};
            Integer result = Graph.businessTrip(flights, invalidTrip);

            assertNull(result);
        }

        @Test
        public void testBusinessTripWithSingleCity() {
            HashMap<String, HashMap<String, Integer>> flights = new HashMap<>();
            flights.put("SingleCity", new HashMap<String, Integer>(){{put("AnotherCity", 60);}});

            String[] singleCityTrip = {"SingleCity"};
            Integer result = Graph.businessTrip(flights, singleCityTrip);

            assertEquals(Integer.valueOf(0), result);
        }
}
