/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedListChallenge;

public class App {
    public static void main(String[] args) {
        LinkedList myList= new LinkedList();
        myList.insert(10);
        myList.insert(20);
        myList.insert(30);

        System.out.println(myList.includes(60));
        System.out.println(myList.to_string());
    }
}
