/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge26;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testSortUnsortedArray() {
        InsertionSort sorter = new InsertionSort();
        int[] arr = {12, 11, 13, 5, 6};
        sorter.sort(arr);
        int[] expected = {5, 6, 11, 12, 13};
        assertArrayEquals(expected, arr);
    }

    @Test
    public void testSortArrayWithDuplicates() {
        InsertionSort sorter = new InsertionSort();
        int[] arr = {9, 7, 9, 1, 3, 7};
        sorter.sort(arr);
        int[] expected = {1, 3, 7, 7, 9, 9};
        assertArrayEquals(expected, arr);
    }

    @Test
    public void testSortEmptyArray() {
        InsertionSort sorter = new InsertionSort();
        int[] arr = {};
        sorter.sort(arr);
        int[] expected = {};
        assertArrayEquals(expected, arr);
    }

    @Test
    public void testSortSingleElementArray() {
        InsertionSort sorter = new InsertionSort();
        int[] arr = {42};
        sorter.sort(arr);
        int[] expected = {42};
        assertArrayEquals(expected, arr);
    }
}
