/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge26;

public class App {
    public static void main(String[] args) {
        InsertionSort array1 = new InsertionSort();
        int[] array = {20,18,12,8,5,-2};
        array1.sort(array);

        System.out.print("[");
        for (int i = 0; i < array.length; i++) {
            System.out.print(array[i]);
            if (i < array.length - 1) {
                System.out.print(", ");
            }
        }
        System.out.println("]");
    }
}
