/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge13;

public class App {
    public static void main(String[] args) {
        BalancedParentheses check= new BalancedParentheses();
        String expression1= "{[hi]}";
        String expression2= "()[[Extra Characters]]";
        String expression3= ")";
        String expression4= "{[}";

        System.out.println(check.validateBrackets(expression1));
        System.out.println(check.validateBrackets(expression2));
        System.out.println(check.validateBrackets(expression3));
        System.out.println(check.validateBrackets(expression4));

    }
}
