/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge12;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {

        AnimalShelter shelter=new AnimalShelter();
        List<Animal<String>> animals = new ArrayList<>();

        animals.add(new Animal<>("spike", "dog"));
        animals.add(new Animal<>("lucy", "cat"));
        animals.add(new Animal<>("Masha", "cat"));
        animals.add(new Animal<>("Rex", "dog"));
        animals.add(new Animal<>("Bella", "cat"));

        for (Animal<String> animal : animals) {
            shelter.enqueue(animal);
        }
        Animal<String> adoptedAnimal = shelter.dequeue("cat");
        if (adoptedAnimal != null) {
            System.out.println("After calling shelter.dequeue(\"cat\"): Name: " + adoptedAnimal.getName() + ", Species: " + adoptedAnimal.getSpecies());
        }

        adoptedAnimal = shelter.dequeue("dog");
        if (adoptedAnimal != null) {
            System.out.println("After calling shelter.dequeue(\"dog\"): Name: " + adoptedAnimal.getName() + ", Species: " + adoptedAnimal.getSpecies());
        }
    }
}
