/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge8;

public class App {
    public static void main(String[] args) {
        LinkedList list1 = new LinkedList();
        list1.append(1);
        list1.append(3);
        list1.append(2);

        LinkedList list2 = new LinkedList();
        list2.append(5);
        list2.append(9);
        list2.append(4);

        Node zippedList = LinkedList.zipLists(list1.head, list2.head);

        while (zippedList != null) {
            System.out.print("{"+zippedList.value+"}" + " -> ");
            zippedList = zippedList.next;
        }
        System.out.println("null");
    }
}
