/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge7;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;

class AppTest {
    private LinkedList list;

    @BeforeEach
    void setUp() {
        list = new LinkedList();
        list.append(1);
        list.append(2);
        list.append(3);
        list.append(4);
        list.append(5);
    }
    @Test
    void kIsGreaterThanTheLength() {
        assertThrows(IllegalArgumentException.class, () -> {
            list.kthNumber(6);
        });
    }

    @Test
    void kEqualsTheLength() {
        assertThrows(IllegalArgumentException.class, () -> {
            list.kthNumber(5);
        });
    }

    @Test
    void kLessThan0() {
        assertThrows(IllegalArgumentException.class, () -> {
            list.kthNumber(-1);
        });
    }

    @Test
    void ListSizeIsOne() {
        LinkedList singleElementList = new LinkedList();
        singleElementList.append(10);
        assertEquals(10, singleElementList.kthNumber(0));
    }

    @Test
    void HappyPath() {
        assertEquals(3, list.kthNumber(2));
    }
}
