/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge15;

public class App {
    public static void main(String[] args) {
        BinarySearchTree tree = new BinarySearchTree();
        tree.add(5);
        tree.add(3);
        tree.add(8);
        tree.add(1);
        tree.add(4);
        tree.add(7);
        tree.add(9);

        System.out.println("Contains 4: " + tree.contains(4));
        System.out.println("Contains 6: " + tree.contains(6));


        System.out.println("Preorder Traversal: " + tree.preOrder());
        System.out.println("Inorder Traversal: " + tree.inOrder());
        System.out.println("Postorder Traversal: " + tree.postOrder());
    }
}
