/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge7;
public class App {
    public static void main(String[] args) {
        LinkedList list = new LinkedList();
        list.append(1);
        list.append(2);
        list.append(3);
        list.append(4);
        list.append(5);

        System.out.println("Linked List: " + list.to_string());
        int k = 2;
        try {
            System.out.println("Value at k=" + k + " from the end: " + list.kthNumber(k));
        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
        }

    }
}
