/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackandqueues;

public class App {
    public static void main(String[] args) {
        System.out.println("Stack Implementation:");
        Stack stackObj= new Stack();
        System.out.println(stackObj.isEmpty());
        stackObj.push(1);
        stackObj.push(2);
        stackObj.push(3);
        System.out.println(stackObj.isEmpty());
        System.out.println(stackObj);
        System.out.println("TopStack: "+stackObj.peek());
        System.out.println("RemovedElement: "+stackObj.pop());
        System.out.println("StackAfterRemovingTop: "+stackObj);
//  ===================================================================
        System.out.println("Queue Implementation:");
            Queue queueObj= new Queue();
            System.out.println(queueObj.isEmpty());
            queueObj.enQueue(4);
            queueObj.enQueue(5);
            queueObj.enQueue(6);
            System.out.println(queueObj.isEmpty());
            System.out.println(queueObj);
            System.out.println("Front: "+queueObj.peek());
            System.out.println("RemovedElement: "+queueObj.deQueue());
            System.out.println("QueueAfterRemovingFront: "+queueObj);
    }
}
