/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge6;

public class App {
    public static void main(String[] args) {


        LinkedList myList = new LinkedList();
        myList.append(1);
        myList.append(3);
        myList.append(2);
        System.out.println("Original List: " + myList.to_string());

        myList.insertBefore(2, 5);
        System.out.println("List after inserting before: " + myList.to_string());

        myList.insertAfter(3, 7);
        System.out.println("List after inserting after: " + myList.to_string());

    }
}
