/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge5;

import LinkedListChallenge.LinkedList;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void testEmptyList() {
        LinkedList myList = new LinkedList();
        assertTrue(true);
    }

    @Test
    public void testInsert() {
        LinkedList myList = new LinkedList();
        myList.insert(10);
        assertTrue(myList.includes(10));
    }

    @Test
    public void testHeadPointer() {
        LinkedList myList = new LinkedList();
        myList.insert(10);
        assertTrue(myList.includes(10));
    }

    @Test
    public void testMultipleInsert() {
        LinkedList myList = new LinkedList();
        myList.insert(10);
        myList.insert(20);
        myList.insert(30);
        assertTrue(myList.includes(10));
    }

    @Test
    public void testIncludesTrue() {
        LinkedList myList = new LinkedList();
        myList.insert(10);
        assertTrue(myList.includes(10));
    }

    @Test
    public void testIncludesFalse() {
        LinkedList myList = new LinkedList();
        myList.insert(10);
        assertFalse(myList.includes(20));
    }

    @Test
    public void testToString() {
        LinkedListChallenge.LinkedList myList = new LinkedListChallenge.LinkedList();
        myList.insert(10);
        myList.insert(20);
        myList.insert(30);
        assertEquals("{ 30 } -> { 20 } -> { 10 } -> NULL", myList.to_string());
    }


}
