/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge6;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

public class AppTest {

    @Test
    public void testAppendSingleNode() {
        LinkedList list = new LinkedList();
        list.append(10);
        assertEquals("10 -> null", list.to_string());
    }

    @Test
    public void testAppendMultipleNodes() {
        LinkedList list = new LinkedList();
        list.append(10);
        list.append(20);
        list.append(30);
        assertEquals("10 -> 20 -> 30 -> null", list.to_string());
    }

    @Test
    public void testInsertBeforeMiddleNode() {
        LinkedList list = new LinkedList();
        list.append(10);
        list.append(30);
        list.insertBefore(30, 25);
        assertEquals("10 -> 25 -> 30 -> null", list.to_string());
    }

    @Test
    public void testInsertBeforeFirstNode() {
        LinkedList list = new LinkedList();
        list.append(20);
        list.insertBefore(20, 15);
        assertEquals("15 -> 20 -> null", list.to_string());
    }

    @Test
    public void testInsertAfterMiddleNode() {
        LinkedList list = new LinkedList();
        list.append(10);
        list.append(30);
        list.insertAfter(10, 15);
        assertEquals("10 -> 15 -> 30 -> null", list.to_string());
    }

    @Test
    public void testInsertAfterLastNode() {
        LinkedList list = new LinkedList();
        list.append(10);
        list.append(20);
        list.insertAfter(20, 25);
        assertEquals("10 -> 20 -> 25 -> null", list.to_string());
    }
}
