/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge33;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static challenge33.LeftJoin.leftJoin;

public class App {
    public static void main(String[] args) {
        Map<String, String> synonyms = new HashMap<>();
        synonyms.put("diligent", "employed");
        synonyms.put("fond", "enamored");
        synonyms.put("guide", "usher");
        synonyms.put("outfit", "garb");
        synonyms.put("wrath", "anger");

        Map<String, String> antonyms = new HashMap<>();
        antonyms.put("diligent", "idle");
        antonyms.put("fond", "averse");
        antonyms.put("guide", "follow");
        antonyms.put("flow", "jam");
        antonyms.put("wrath", "delight");

        List<List<String>> result = leftJoin(synonyms, antonyms);
        System.out.println("[");
        for (List<String> row : result) {
            System.out.println(row);
        }
        System.out.println("]");
    }
}
