/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge28;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class App {
    public static void main(String[] args) {

        List<Movie> movies = new ArrayList<>();

        movies.add(new Movie("The Amazing Spider-man", 2002, List.of("Action", "Drama")));
        movies.add(new Movie("The Dark Knight", 2008, List.of("Action", "Drama")));
        movies.add(new Movie("The Godfather", 1972, List.of("Crime", "Drama")));
        movies.add(new Movie("Pulp Fiction", 1994, List.of("Crime", "Drama")));
        movies.add(new Movie("Inception", 2010, List.of("Action", "Sci-Fi")));

        Collections.sort(movies, MovieComparators.sortByYearDescending());

        System.out.println("Sorted by Year (Descending):");
        for (Movie movie : movies) {
            System.out.println(movie.getTitle() + " (" + movie.getYear() + ")");
        }

        List<String> ignoredWords = List.of("The", "An");
        Collections.sort(movies, MovieComparators.sortByTitleIgnoringWords(ignoredWords));

        System.out.println("\nSorted by Title (Ignoring 'The' and 'An'):");
        for (Movie movie : movies) {
            System.out.println(movie.getTitle());
        }
    }
}
